import { QuranTopic, RabbanaDua, SurahMeta } from "../types";

export const ALL_SURAHS: SurahMeta[] = [
  {
    number: 1,
    name_arabic: "الفاتحة",
    name_english: "The Opening",
    name_roman: "Al-Fatihah",
    ayah_count: 7,
    place_of_revelation: "Meccan",
  },
  {
    number: 2,
    name_arabic: "البقرة",
    name_english: "The Cow",
    name_roman: "Al-Baqarah",
    ayah_count: 286,
    place_of_revelation: "Medinan",
  },
  {
    number: 3,
    name_arabic: "آل عمران",
    name_english: "Family of Imran",
    name_roman: "Ali 'Imran",
    ayah_count: 200,
    place_of_revelation: "Medinan",
  },
  {
    number: 4,
    name_arabic: "النساء",
    name_english: "The Women",
    name_roman: "An-Nisa",
    ayah_count: 176,
    place_of_revelation: "Medinan",
  },
  {
    number: 5,
    name_arabic: "المائدة",
    name_english: "The Table Spread",
    name_roman: "Al-Ma'idah",
    ayah_count: 120,
    place_of_revelation: "Medinan",
  },
  {
    number: 6,
    name_arabic: "الأنعام",
    name_english: "The Cattle",
    name_roman: "Al-An'am",
    ayah_count: 165,
    place_of_revelation: "Meccan",
  },
  {
    number: 7,
    name_arabic: "الأعراف",
    name_english: "The Heights",
    name_roman: "Al-A'raf",
    ayah_count: 206,
    place_of_revelation: "Meccan",
  },
  {
    number: 8,
    name_arabic: "الأنفال",
    name_english: "The Spoils of War",
    name_roman: "Al-Anfal",
    ayah_count: 75,
    place_of_revelation: "Medinan",
  },
  {
    number: 9,
    name_arabic: "التوبة",
    name_english: "The Repentance",
    name_roman: "At-Tawbah",
    ayah_count: 129,
    place_of_revelation: "Medinan",
  },
  {
    number: 10,
    name_arabic: "يونس",
    name_english: "Jonah",
    name_roman: "Yunus",
    ayah_count: 109,
    place_of_revelation: "Meccan",
  },
  {
    number: 11,
    name_arabic: "هود",
    name_english: "Hud",
    name_roman: "Hud",
    ayah_count: 123,
    place_of_revelation: "Meccan",
  },
  {
    number: 12,
    name_arabic: "يوسف",
    name_english: "Joseph",
    name_roman: "Yusuf",
    ayah_count: 111,
    place_of_revelation: "Meccan",
  },
  {
    number: 13,
    name_arabic: "الرعد",
    name_english: "The Thunder",
    name_roman: "Ar-Ra'd",
    ayah_count: 43,
    place_of_revelation: "Medinan",
  },
  {
    number: 14,
    name_arabic: "إبراهيم",
    name_english: "Abraham",
    name_roman: "Ibrahim",
    ayah_count: 52,
    place_of_revelation: "Meccan",
  },
  {
    number: 15,
    name_arabic: "الحجر",
    name_english: "The Rocky Tract",
    name_roman: "Al-Hijr",
    ayah_count: 99,
    place_of_revelation: "Meccan",
  },
  {
    number: 16,
    name_arabic: "النحل",
    name_english: "The Bee",
    name_roman: "An-Nahl",
    ayah_count: 128,
    place_of_revelation: "Meccan",
  },
  {
    number: 17,
    name_arabic: "الإسراء",
    name_english: "The Night Journey",
    name_roman: "Al-Isra",
    ayah_count: 111,
    place_of_revelation: "Meccan",
  },
  {
    number: 18,
    name_arabic: "الكهف",
    name_english: "The Cave",
    name_roman: "Al-Kahf",
    ayah_count: 110,
    place_of_revelation: "Meccan",
  },
  {
    number: 19,
    name_arabic: "مريم",
    name_english: "Mary",
    name_roman: "Maryam",
    ayah_count: 98,
    place_of_revelation: "Meccan",
  },
  {
    number: 20,
    name_arabic: "طه",
    name_english: "Ta-Ha",
    name_roman: "Taha",
    ayah_count: 135,
    place_of_revelation: "Meccan",
  },
  {
    number: 21,
    name_arabic: "الأنبياء",
    name_english: "The Prophets",
    name_roman: "Al-Anbiya",
    ayah_count: 112,
    place_of_revelation: "Meccan",
  },
  {
    number: 22,
    name_arabic: "الحج",
    name_english: "The Pilgrimage",
    name_roman: "Al-Hajj",
    ayah_count: 78,
    place_of_revelation: "Medinan",
  },
  {
    number: 23,
    name_arabic: "المؤمنون",
    name_english: "The Believers",
    name_roman: "Al-Mu'minun",
    ayah_count: 118,
    place_of_revelation: "Meccan",
  },
  {
    number: 24,
    name_arabic: "النور",
    name_english: "The Light",
    name_roman: "An-Nur",
    ayah_count: 64,
    place_of_revelation: "Medinan",
  },
  {
    number: 25,
    name_arabic: "الفرقان",
    name_english: "The Criterion",
    name_roman: "Al-Furqan",
    ayah_count: 77,
    place_of_revelation: "Meccan",
  },
  {
    number: 26,
    name_arabic: "الشعراء",
    name_english: "The Poets",
    name_roman: "Ash-Shu'ara",
    ayah_count: 227,
    place_of_revelation: "Meccan",
  },
  {
    number: 27,
    name_arabic: "النمل",
    name_english: "The Ant",
    name_roman: "An-Naml",
    ayah_count: 93,
    place_of_revelation: "Meccan",
  },
  {
    number: 28,
    name_arabic: "القصص",
    name_english: "The Stories",
    name_roman: "Al-Qasas",
    ayah_count: 88,
    place_of_revelation: "Meccan",
  },
  {
    number: 29,
    name_arabic: "العنكبوت",
    name_english: "The Spider",
    name_roman: "Al-'Ankabut",
    ayah_count: 69,
    place_of_revelation: "Meccan",
  },
  {
    number: 30,
    name_arabic: "الروم",
    name_english: "The Romans",
    name_roman: "Ar-Rum",
    ayah_count: 60,
    place_of_revelation: "Meccan",
  },
  {
    number: 31,
    name_arabic: "لقمان",
    name_english: "Luqman",
    name_roman: "Luqman",
    ayah_count: 34,
    place_of_revelation: "Meccan",
  },
  {
    number: 32,
    name_arabic: "السجدة",
    name_english: "The Prostration",
    name_roman: "As-Sajdah",
    ayah_count: 30,
    place_of_revelation: "Meccan",
  },
  {
    number: 33,
    name_arabic: "الأحزاب",
    name_english: "The Combined Forces",
    name_roman: "Al-Ahzab",
    ayah_count: 73,
    place_of_revelation: "Medinan",
  },
  {
    number: 34,
    name_arabic: "سبأ",
    name_english: "Sheba",
    name_roman: "Saba",
    ayah_count: 54,
    place_of_revelation: "Meccan",
  },
  {
    number: 35,
    name_arabic: "فاطر",
    name_english: "Originator",
    name_roman: "Fatir",
    ayah_count: 45,
    place_of_revelation: "Meccan",
  },
  {
    number: 36,
    name_arabic: "يس",
    name_english: "Ya-Sin",
    name_roman: "Ya-Sin",
    ayah_count: 83,
    place_of_revelation: "Meccan",
  },
  {
    number: 37,
    name_arabic: "الصافات",
    name_english: "Those who set the Ranks",
    name_roman: "As-Saffat",
    ayah_count: 182,
    place_of_revelation: "Meccan",
  },
  {
    number: 38,
    name_arabic: "ص",
    name_english: "The Letter Sad",
    name_roman: "Sad",
    ayah_count: 88,
    place_of_revelation: "Meccan",
  },
  {
    number: 39,
    name_arabic: "الزمر",
    name_english: "The Troops",
    name_roman: "Az-Zumar",
    ayah_count: 75,
    place_of_revelation: "Meccan",
  },
  {
    number: 40,
    name_arabic: "غافر",
    name_english: "The Forgiver",
    name_roman: "Ghafir",
    ayah_count: 85,
    place_of_revelation: "Meccan",
  },
  {
    number: 41,
    name_arabic: "فصلت",
    name_english: "Explained in Detail",
    name_roman: "Fussilat",
    ayah_count: 54,
    place_of_revelation: "Meccan",
  },
  {
    number: 42,
    name_arabic: "الشورى",
    name_english: "The Consultation",
    name_roman: "Ash-Shura",
    ayah_count: 53,
    place_of_revelation: "Meccan",
  },
  {
    number: 43,
    name_arabic: "الزخرف",
    name_english: "The Ornaments of Gold",
    name_roman: "Az-Zukhruf",
    ayah_count: 89,
    place_of_revelation: "Meccan",
  },
  {
    number: 44,
    name_arabic: "الدخان",
    name_english: "The Smoke",
    name_roman: "Ad-Dukhan",
    ayah_count: 59,
    place_of_revelation: "Meccan",
  },
  {
    number: 45,
    name_arabic: "الجاثية",
    name_english: "The Crouching",
    name_roman: "Al-Jathiyah",
    ayah_count: 37,
    place_of_revelation: "Meccan",
  },
  {
    number: 46,
    name_arabic: "الأحقاف",
    name_english: "The Wind-Curved Sandhills",
    name_roman: "Al-Ahqaf",
    ayah_count: 35,
    place_of_revelation: "Meccan",
  },
  {
    number: 47,
    name_arabic: "محمد",
    name_english: "Muhammad",
    name_roman: "Muhammad",
    ayah_count: 38,
    place_of_revelation: "Medinan",
  },
  {
    number: 48,
    name_arabic: "الفتح",
    name_english: "The Victory",
    name_roman: "Al-Fath",
    ayah_count: 29,
    place_of_revelation: "Medinan",
  },
  {
    number: 49,
    name_arabic: "الحجرات",
    name_english: "The Rooms",
    name_roman: "Al-Hujurat",
    ayah_count: 18,
    place_of_revelation: "Medinan",
  },
  {
    number: 50,
    name_arabic: "ق",
    name_english: "The Letter Qaf",
    name_roman: "Qaf",
    ayah_count: 45,
    place_of_revelation: "Meccan",
  },
  {
    number: 51,
    name_arabic: "الذاريات",
    name_english: "The Winnowing Winds",
    name_roman: "Adh-Dhariyat",
    ayah_count: 60,
    place_of_revelation: "Meccan",
  },
  {
    number: 52,
    name_arabic: "الطور",
    name_english: "The Mount",
    name_roman: "At-Tur",
    ayah_count: 49,
    place_of_revelation: "Meccan",
  },
  {
    number: 53,
    name_arabic: "النجم",
    name_english: "The Star",
    name_roman: "An-Najm",
    ayah_count: 62,
    place_of_revelation: "Meccan",
  },
  {
    number: 54,
    name_arabic: "القمر",
    name_english: "The Moon",
    name_roman: "Al-Qamar",
    ayah_count: 55,
    place_of_revelation: "Meccan",
  },
  {
    number: 55,
    name_arabic: "الرحمن",
    name_english: "The Beneficent",
    name_roman: "Ar-Rahman",
    ayah_count: 78,
    place_of_revelation: "Medinan",
  },
  {
    number: 56,
    name_arabic: "الواقعة",
    name_english: "The Inevitable",
    name_roman: "Al-Waqi'ah",
    ayah_count: 96,
    place_of_revelation: "Meccan",
  },
  {
    number: 57,
    name_arabic: "الحديد",
    name_english: "The Iron",
    name_roman: "Al-Hadid",
    ayah_count: 29,
    place_of_revelation: "Medinan",
  },
  {
    number: 58,
    name_arabic: "المجادلة",
    name_english: "The Pleading Woman",
    name_roman: "Al-Mujadila",
    ayah_count: 22,
    place_of_revelation: "Medinan",
  },
  {
    number: 59,
    name_arabic: "الحشر",
    name_english: "The Exile",
    name_roman: "Al-Hashr",
    ayah_count: 24,
    place_of_revelation: "Medinan",
  },
  {
    number: 60,
    name_arabic: "الممتحنة",
    name_english: "She that is to be examined",
    name_roman: "Al-Mumtahanah",
    ayah_count: 13,
    place_of_revelation: "Medinan",
  },
  {
    number: 61,
    name_arabic: "الصف",
    name_english: "The Ranks",
    name_roman: "As-Saff",
    ayah_count: 14,
    place_of_revelation: "Medinan",
  },
  {
    number: 62,
    name_arabic: "الجمعة",
    name_english: "The Congregation",
    name_roman: "Al-Jumu'ah",
    ayah_count: 11,
    place_of_revelation: "Medinan",
  },
  {
    number: 63,
    name_arabic: "المنافقون",
    name_english: "The Hypocrites",
    name_roman: "Al-Munafiqun",
    ayah_count: 11,
    place_of_revelation: "Medinan",
  },
  {
    number: 64,
    name_arabic: "التغابن",
    name_english: "The Mutual Disillusion",
    name_roman: "At-Taghabun",
    ayah_count: 18,
    place_of_revelation: "Medinan",
  },
  {
    number: 65,
    name_arabic: "الطلاق",
    name_english: "The Divorce",
    name_roman: "At-Talaq",
    ayah_count: 12,
    place_of_revelation: "Medinan",
  },
  {
    number: 66,
    name_arabic: "التحريم",
    name_english: "The Prohibition",
    name_roman: "At-Tahrim",
    ayah_count: 12,
    place_of_revelation: "Medinan",
  },
  {
    number: 67,
    name_arabic: "الملك",
    name_english: "The Sovereignty",
    name_roman: "Al-Mulk",
    ayah_count: 30,
    place_of_revelation: "Meccan",
  },
  {
    number: 68,
    name_arabic: "القلم",
    name_english: "The Pen",
    name_roman: "Al-Qalam",
    ayah_count: 52,
    place_of_revelation: "Meccan",
  },
  {
    number: 69,
    name_arabic: "الحاقة",
    name_english: "The Reality",
    name_roman: "Al-Haqqah",
    ayah_count: 52,
    place_of_revelation: "Meccan",
  },
  {
    number: 70,
    name_arabic: "المعارج",
    name_english: "The Ascending Stairways",
    name_roman: "Al-Ma'arij",
    ayah_count: 44,
    place_of_revelation: "Meccan",
  },
  {
    number: 71,
    name_arabic: "نوح",
    name_english: "Noah",
    name_roman: "Nuh",
    ayah_count: 28,
    place_of_revelation: "Meccan",
  },
  {
    number: 72,
    name_arabic: "الجن",
    name_english: "The Jinn",
    name_roman: "Al-Jinn",
    ayah_count: 28,
    place_of_revelation: "Meccan",
  },
  {
    number: 73,
    name_arabic: "المزمل",
    name_english: "The Enshrouded One",
    name_roman: "Al-Muzzammil",
    ayah_count: 20,
    place_of_revelation: "Meccan",
  },
  {
    number: 74,
    name_arabic: "المدثر",
    name_english: "The Cloaked One",
    name_roman: "Al-Muddaththir",
    ayah_count: 56,
    place_of_revelation: "Meccan",
  },
  {
    number: 75,
    name_arabic: "القيامة",
    name_english: "The Resurrection",
    name_roman: "Al-Qiyamah",
    ayah_count: 40,
    place_of_revelation: "Meccan",
  },
  {
    number: 76,
    name_arabic: "الإنسان",
    name_english: "The Human",
    name_roman: "Al-Insan",
    ayah_count: 31,
    place_of_revelation: "Medinan",
  },
  {
    number: 77,
    name_arabic: "المرسلات",
    name_english: "The Emissaries",
    name_roman: "Al-Mursalat",
    ayah_count: 50,
    place_of_revelation: "Meccan",
  },
  {
    number: 78,
    name_arabic: "النبأ",
    name_english: "The Tidings",
    name_roman: "An-Naba",
    ayah_count: 40,
    place_of_revelation: "Meccan",
  },
  {
    number: 79,
    name_arabic: "النازعات",
    name_english: "Those who drag forth",
    name_roman: "An-Nazi'at",
    ayah_count: 46,
    place_of_revelation: "Meccan",
  },
  {
    number: 80,
    name_arabic: "عبس",
    name_english: "He frowned",
    name_roman: "'Abasa",
    ayah_count: 42,
    place_of_revelation: "Meccan",
  },
  {
    number: 81,
    name_arabic: "التكوير",
    name_english: "The Overthrowing",
    name_roman: "At-Takwir",
    ayah_count: 29,
    place_of_revelation: "Meccan",
  },
  {
    number: 82,
    name_arabic: "الانفطار",
    name_english: "The Cleaving",
    name_roman: "Al-Infitar",
    ayah_count: 19,
    place_of_revelation: "Meccan",
  },
  {
    number: 83,
    name_arabic: "المطففين",
    name_english: "The Defrauding",
    name_roman: "Al-Mutaffifin",
    ayah_count: 36,
    place_of_revelation: "Meccan",
  },
  {
    number: 84,
    name_arabic: "الانشقاق",
    name_english: "The Splitting Open",
    name_roman: "Al-Inshiqaq",
    ayah_count: 25,
    place_of_revelation: "Meccan",
  },
  {
    number: 85,
    name_arabic: "البروج",
    name_english: "The Mansions of the Stars",
    name_roman: "Al-Buruj",
    ayah_count: 22,
    place_of_revelation: "Meccan",
  },
  {
    number: 86,
    name_arabic: "الطارق",
    name_english: "The Morning Star",
    name_roman: "At-Tariq",
    ayah_count: 17,
    place_of_revelation: "Meccan",
  },
  {
    number: 87,
    name_arabic: "الأعلى",
    name_english: "The Most High",
    name_roman: "Al-A'la",
    ayah_count: 19,
    place_of_revelation: "Meccan",
  },
  {
    number: 88,
    name_arabic: "الغاشية",
    name_english: "The Overwhelming",
    name_roman: "Al-Ghashiyah",
    ayah_count: 26,
    place_of_revelation: "Meccan",
  },
  {
    number: 89,
    name_arabic: "الفجر",
    name_english: "The Dawn",
    name_roman: "Al-Fajr",
    ayah_count: 30,
    place_of_revelation: "Meccan",
  },
  {
    number: 90,
    name_arabic: "البلد",
    name_english: "The City",
    name_roman: "Al-Balad",
    ayah_count: 20,
    place_of_revelation: "Meccan",
  },
  {
    number: 91,
    name_arabic: "الشمس",
    name_english: "The Sun",
    name_roman: "Ash-Shams",
    ayah_count: 15,
    place_of_revelation: "Meccan",
  },
  {
    number: 92,
    name_arabic: "الليل",
    name_english: "The Night",
    name_roman: "Al-Layl",
    ayah_count: 21,
    place_of_revelation: "Meccan",
  },
  {
    number: 93,
    name_arabic: "الضحى",
    name_english: "The Morning Hours",
    name_roman: "Ad-Duha",
    ayah_count: 11,
    place_of_revelation: "Meccan",
  },
  {
    number: 94,
    name_arabic: "الشرح",
    name_english: "The Relief",
    name_roman: "Ash-Sharh",
    ayah_count: 8,
    place_of_revelation: "Meccan",
  },
  {
    number: 95,
    name_arabic: "التين",
    name_english: "The Fig",
    name_roman: "At-Tin",
    ayah_count: 8,
    place_of_revelation: "Meccan",
  },
  {
    number: 96,
    name_arabic: "العلق",
    name_english: "The Clot",
    name_roman: "Al-'Alaq",
    ayah_count: 19,
    place_of_revelation: "Meccan",
  },
  {
    number: 97,
    name_arabic: "القدر",
    name_english: "The Power",
    name_roman: "Al-Qadr",
    ayah_count: 5,
    place_of_revelation: "Meccan",
  },
  {
    number: 98,
    name_arabic: "البينة",
    name_english: "The Clear Proof",
    name_roman: "Al-Bayyinah",
    ayah_count: 8,
    place_of_revelation: "Medinan",
  },
  {
    number: 99,
    name_arabic: "الزلزلة",
    name_english: "The Earthquake",
    name_roman: "Az-Zalzalah",
    ayah_count: 8,
    place_of_revelation: "Medinan",
  },
  {
    number: 100,
    name_arabic: "العاديات",
    name_english: "The Courser",
    name_roman: "Al-'Adiyat",
    ayah_count: 11,
    place_of_revelation: "Meccan",
  },
  {
    number: 101,
    name_arabic: "القارعة",
    name_english: "The Calamity",
    name_roman: "Al-Qari'ah",
    ayah_count: 11,
    place_of_revelation: "Meccan",
  },
  {
    number: 102,
    name_arabic: "التكاثر",
    name_english: "The Rivalry in World Increase",
    name_roman: "At-Takathur",
    ayah_count: 8,
    place_of_revelation: "Meccan",
  },
  {
    number: 103,
    name_arabic: "العصر",
    name_english: "The Declining Day",
    name_roman: "Al-'Asr",
    ayah_count: 3,
    place_of_revelation: "Meccan",
  },
  {
    number: 104,
    name_arabic: "الهمزة",
    name_english: "The Traducer",
    name_roman: "Al-Humazah",
    ayah_count: 9,
    place_of_revelation: "Meccan",
  },
  {
    number: 105,
    name_arabic: "الفيل",
    name_english: "The Elephant",
    name_roman: "Al-Fil",
    ayah_count: 5,
    place_of_revelation: "Meccan",
  },
  {
    number: 106,
    name_arabic: "قريش",
    name_english: "Quraysh",
    name_roman: "Quraysh",
    ayah_count: 4,
    place_of_revelation: "Meccan",
  },
  {
    number: 107,
    name_arabic: "الماعون",
    name_english: "The Small Kindness",
    name_roman: "Al-Ma'un",
    ayah_count: 7,
    place_of_revelation: "Meccan",
  },
  {
    number: 108,
    name_arabic: "الكوثر",
    name_english: "The Abundance",
    name_roman: "Al-Kawthar",
    ayah_count: 3,
    place_of_revelation: "Meccan",
  },
  {
    number: 109,
    name_arabic: "الكافرون",
    name_english: "The Disbelievers",
    name_roman: "Al-Kafirun",
    ayah_count: 6,
    place_of_revelation: "Meccan",
  },
  {
    number: 110,
    name_arabic: "النصر",
    name_english: "The Divine Support",
    name_roman: "An-Nasr",
    ayah_count: 3,
    place_of_revelation: "Medinan",
  },
  {
    number: 111,
    name_arabic: "المسد",
    name_english: "The Palm Fiber",
    name_roman: "Al-Masad",
    ayah_count: 5,
    place_of_revelation: "Meccan",
  },
  {
    number: 112,
    name_arabic: "الإخلاص",
    name_english: "The Sincerity",
    name_roman: "Al-Ikhlas",
    ayah_count: 4,
    place_of_revelation: "Meccan",
  },
  {
    number: 113,
    name_arabic: "الفلق",
    name_english: "The Daybreak",
    name_roman: "Al-Falaq",
    ayah_count: 5,
    place_of_revelation: "Meccan",
  },
  {
    number: 114,
    name_arabic: "الناس",
    name_english: "Mankind",
    name_roman: "An-Nas",
    ayah_count: 6,
    place_of_revelation: "Meccan",
  },
];

export const QURAN_TOPICS: QuranTopic[] = [
  {
    id: "sabr",
    title: "Patience & Perseverance",
    arabicTitle: "الصبر والتحمل",
    description:
      "Verses addressing resilience, trusting Allah's timing, and endurance through trials.",
    icon: "Shield",
    sampleQueries: [
      "What does the Quran say about patience (Sabr) in times of difficulty?",
      "How is patience rewarded according to the Quran?",
      "What did Prophet Ya'qub say about beautiful patience (Sabrun Jameel)?",
    ],
    keyVerses: ["2:153", "2:155-156", "3:200", "39:10"],
  },
  {
    id: "tawakkul",
    title: "Reliance on Allah (Tawakkul)",
    arabicTitle: "التوكل على الله",
    description:
      "Deep trust in Divine wisdom while undertaking purposeful action.",
    icon: "HeartHandshake",
    sampleQueries: [
      "What are the verses about trusting Allah (Tawakkul)?",
      "How does Allah describe those who rely upon Him?",
      "Where does it say Allah is sufficient for the believer?",
    ],
    keyVerses: ["65:3", "3:159", "8:2", "9:51"],
  },
  {
    id: "gratitude",
    title: "Gratitude & Contentment (Shukr)",
    arabicTitle: "الشكر والرضا",
    description:
      "Recognizing blessings, increasing favor through thankfulness, and inner peace.",
    icon: "Sparkles",
    sampleQueries: [
      "What is the promise in the Quran for those who are grateful?",
      "How does gratitude affect a believer's heart in Quranic wisdom?",
      "Which verses in Surah Ar-Rahman ask 'Which favors of your Lord will you deny?'",
    ],
    keyVerses: ["14:7", "2:152", "55:13", "31:12"],
  },
  {
    id: "justice",
    title: "Justice, Truth & Integrity",
    arabicTitle: "العدل والقسط",
    description:
      "Standing firmly for justice, honest commerce, and upright character.",
    icon: "Scale",
    sampleQueries: [
      "What does the Quran command regarding justice even against oneself?",
      "What does Islam teach about honesty in trade and measures?",
      "Verses about standing as witnesses to truth",
    ],
    keyVerses: ["4:135", "5:8", "16:90", "83:1-3"],
  },
  {
    id: "parents",
    title: "Kindness to Parents & Family",
    arabicTitle: "بر الوالدين والأرحام",
    description:
      "Honoring parents, gentle speech, and upholding ties of kinship.",
    icon: "Heart",
    sampleQueries: [
      "What does Surah Al-Isra teach about treating aging parents?",
      "What are the Quranic prayers for one's parents?",
      "What are the verses about kindness and mercy between spouses?",
    ],
    keyVerses: ["17:23-24", "31:14", "30:21", "46:15"],
  },
  {
    id: "forgiveness",
    title: "Repentance & Divine Mercy (Tawbah)",
    arabicTitle: "المغفرة والرحمة",
    description:
      "Unconditional hope in Allah's boundless mercy and the path of forgiveness.",
    icon: "Compass",
    sampleQueries: [
      "What does Surah Az-Zumar say to those who have transgressed against themselves?",
      "How vast is Allah's forgiveness in the Quran?",
      "Show me verses about seeking forgiveness in the early dawn.",
    ],
    keyVerses: ["39:53", "3:135", "4:110", "11:90"],
  },
];

export const RABBANA_DUAS: RabbanaDua[] = [
  {
    id: "dua-1",
    verse_id: "2:201",
    arabic:
      "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
    english:
      "Our Lord, give us in this world that which is good and in the Hereafter that which is good and protect us from the punishment of the Fire.",
    context: "Universal prayer for goodness in both worlds.",
    surah_name: "Al-Baqarah (2:201)",
  },
  {
    id: "dua-2",
    verse_id: "3:8",
    arabic:
      "رَبَّنَا لاَ تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ",
    english:
      "Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.",
    context: "Prayer for steadfastness in faith and guidance.",
    surah_name: "Ali 'Imran (3:8)",
  },
  {
    id: "dua-3",
    verse_id: "2:286",
    arabic:
      "رَبَّنَا لاَ تُؤَاخِذْنَا إِن نَّسِينَا أَوْ أَخْطَأْنَا رَبَّنَا وَلاَ تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِن قَبْلِنَا",
    english:
      "Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us.",
    context: "Supplication at the end of Surah Al-Baqarah.",
    surah_name: "Al-Baqarah (2:286)",
  },
  {
    id: "dua-4",
    verse_id: "25:74",
    arabic:
      "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
    english:
      "Our Lord, grant us from among our spouses and offspring comfort to our eyes and make us an example for the righteous.",
    context:
      "Prayer of the servants of the Most Merciful for righteous family.",
    surah_name: "Al-Furqan (25:74)",
  },
  {
    id: "dua-5",
    verse_id: "20:114",
    arabic: "رَّبِّ زِدْنِي عِلْمًا",
    english: "My Lord, increase me in knowledge.",
    context: "Prophetic prayer for divine knowledge and wisdom.",
    surah_name: "Ta-Ha (20:114)",
  },
  {
    id: "dua-6",
    verse_id: "21:87",
    arabic:
      "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
    english:
      "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
    context: "Dua of Prophet Yunus (Jonah) in distress.",
    surah_name: "Al-Anbiya (21:87)",
  },
];

export const CATEGORIZED_PROMPT_SUGGESTIONS = [
  {
    category: "Spiritual Guidance",
    tag: "Core Faith",
    prompts: [
      "What does the Quran say about finding peace of heart through remembrance (Dhikr)?",
      "Explain the concept of Tawakkul (Trust in Allah) and its spiritual benefits.",
      "What are the characteristics of the true believers (Mu'minun) in the Quran?",
      "How does the Quran encourage hope and deter despair?",
    ],
  },
  {
    category: "Wisdom & Life Challenges",
    tag: "Life & Trials",
    prompts: [
      "What does the Quran teach about patience (Sabr) during sudden illness or loss?",
      "What verses discuss financial integrity, honesty in transactions, and avoiding usury?",
      "How should a Muslim respond to injustice and hostility according to Quranic wisdom?",
      "What are the Quran's teachings on kindness, humility, and avoiding arrogance?",
    ],
  },
  {
    category: "Urdu Queries (اردو سوالات)",
    tag: "اردو",
    prompts: [
      "قرآن مجید میں صبر اور شکر کے بارے میں کیا ہدایات ہیں؟",
      "والدین کے ساتھ حسن سلوک سے متعلق قرآنی آیات بتائیں۔",
      "مشکلات اور پریشانی میں کون سی قرآنی دعائیں پڑھنی چاہئیں؟",
      "رزق میں برکت اور اللہ پر توکل کے بارے میں قرآن کیا فرماتا ہے؟",
    ],
  },
  {
    category: "Arabic Reflections (تأملات قرآنية)",
    tag: "العربية",
    prompts: [
      "ما هي الآيات التي تتحدث عن طمأنينة القلب وانشراح الصدر؟",
      "اذكر آيات الصبر والفرج في القرآن الكريم مع شرح موجز.",
      "ما هي وصايا لقمان لابنه في القرآن الكريم؟",
      "آيات الرحمة والمغفرة والتوبة الصادقة",
    ],
  },
];

export interface HeroPrompt {
  id: string;
  lang: "en" | "ur" | "ar";
  label: string;
  query: string;
}

export const CURATED_HERO_PROMPTS: HeroPrompt[] = [
  {
    id: "p-1",
    lang: "en",
    label: "Patience (Sabr) in Hardship",
    query:
      "What does the Quran teach about patience (Sabr) during trials and difficulty?",
  },
  {
    id: "p-2",
    lang: "en",
    label: "Peace of Heart through Dhikr",
    query:
      "What verses discuss finding tranquility and peace of heart through the remembrance of Allah?",
  },
  {
    id: "p-3",
    lang: "ur",
    label: "صبر اور شکر کی فضیلت",
    query:
      "قرآن مجید میں صبر اور شکر کے بارے میں کیا ہدایات اور فضائل بیان ہوئے ہیں؟",
  },
  {
    id: "p-4",
    lang: "ur",
    label: "والدین کے ساتھ حسنِ سلوک",
    query:
      "والدین کی خدمت اور ان کے ساتھ حسنِ سلوک کے بارے میں قرآنی تعلیمات کیا ہیں؟",
  },
  {
    id: "p-5",
    lang: "ar",
    label: "طمأنينة القلب والسكينة",
    query:
      "ما هي الآيات التي تتحدث عن طمأنينة القلب وانشراح الصدر في القرآن الكريم؟",
  },
];
